services:

  namesrv:

    image: apacherocketmq/rocketmq

    container_name: rmqnamesrv

    ports:

      - 19876:9876

    volumes:

      - ./namesrv/logs:/home/rocketmq/logs

    command: sh mqnamesrv

  broker-1:

    image: apacherocketmq/rocketmq

    container_name: rmqbroker-1

    ports:

      - 10909:10909

      - 10911:10911

      - 10912:10912

    volumes:

      - ./broker-1/logs:/home/rocketmq/logs

      - ./broker-1/store:/home/rocketmq/store

      - ./broker-1/conf/broker1.conf:/home/rocketmq/rocketmq-4.6.0/conf/broker.conf

    environment:

      NAMESRV_ADDR: "namesrv:9876"

      JAVA_OPTS: " -Duser.home=/opt"

      JAVA_OPT_EXT: "-server -Xms128m -Xmx128m -Xmn128m"

    command: sh mqbroker -n namesrv:9876 -c ../conf/broker.conf

    depends_on:

      - namesrv

  broker-1-slave:

    image: apacherocketmq/rocketmq

    container_name: rmqbroker-1-slave

    ports:

      - 12909:12909

      - 12911:12911

      - 12912:12912

    volumes:

      - ./broker-1-slave/logs:/home/rocketmq/logs

      - ./broker-1-slave/store:/home/rocketmq/store

      - ./broker-1-slave/conf/broker1.conf:/home/rocketmq/rocketmq-4.6.0/conf/broker.conf

    environment:

      NAMESRV_ADDR: "namesrv:9876"

      JAVA_OPTS: " -Duser.home=/opt"

      JAVA_OPT_EXT: "-server -Xms128m -Xmx128m -Xmn128m"

    command: sh mqbroker -n namesrv:9876 -c ../conf/broker.conf

    depends_on:

      - namesrv

  broker-2:

    image: apacherocketmq/rocketmq

    container_name: rmqbroker-2

    ports:

      - 11909:11909

      - 11911:11911

      - 11912:11912

    volumes:

      - ./broker-2/logs:/home/rocketmq/logs

      - ./broker-2/store:/home/rocketmq/store

      - ./broker-2/conf/broker2.conf:/home/rocketmq/rocketmq-4.6.0/conf/broker.conf

    environment:

      NAMESRV_ADDR: "namesrv:9876"

      JAVA_OPTS: " -Duser.home=/opt"

      JAVA_OPT_EXT: "-server -Xms128m -Xmx128m -Xmn128m"

    command: sh mqbroker -n namesrv:9876 -c ../conf/broker.conf

    depends_on:

      - namesrv

  broker-2-slave:

    image: apacherocketmq/rocketmq

    container_name: rmqbroker-2-slave

    ports:

      - 13909:13909

      - 13911:13911

      - 13912:13912

    volumes:

      - ./broker-2-slave/logs:/home/rocketmq/logs

      - ./broker-2-slave/store:/home/rocketmq/store

      - ./broker-2-slave/conf/broker2.conf:/home/rocketmq/rocketmq-4.6.0/conf/broker.conf

    environment:

      NAMESRV_ADDR: "namesrv:9876"

      JAVA_OPTS: " -Duser.home=/opt"

      JAVA_OPT_EXT: "-server -Xms128m -Xmx128m -Xmn128m"

    command: sh mqbroker -n namesrv:9876 -c ../conf/broker.conf

    depends_on:

      - namesrv

  rmqconsole:

    image: styletang/rocketmq-console-ng

    container_name: rmqconsole

    ports:

      - 18080:8080

    environment:

        JAVA_OPTS: "-Drocketmq.namesrv.addr=namesrv:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false"

    depends_on:

      - namesrv
